## 注意：书写时，缩进不能使用 Tab，必须使用空格

#############################
# 应用程序设置
#############################

# 在这里添加应用程序需要的设置

# 这里的设置可以用 Q::getIni('appini/设置名') 来读取，例如 Q::getIni('appini/app_title');
# 如果要将应用程序设置存入其他的键名中（默认为 appini），则修改 boot.php 中  $root . '/config/app.yaml.php' => 'appini' 代码

